apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-participantes-config
data:
  APP_NAME: ms-participantes
  SERVER_PORT: "9081"
  EVENTOS_SERVICE_URL: http://ms-eventos:9084
  DB_URL: jdbc:oracle:thin:@//oracle-db:1521/XEPDB1
  DB_DRIVER: oracle.jdbc.OracleDriver
  JPA_DDL_AUTO: update
  JPA_SHOW_SQL: "true"
  HIBERNATE_DIALECT: org.hibernate.dialect.OracleDialect
  application.yml: |
    management:
      endpoint:
        health:
          probes:
            enabled: true
      health:
        livenessstate:
          enabled: true
        readinessstate:
          enabled: true
      endpoints:
        web:
          exposure:
            include: health