apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-participantes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-participantes
  template:
    metadata:
      labels:
        app: ms-participantes
    spec:
      containers:
      - name: ms-participantes
        image: jean1988/ms-participantes:1.6
        ports:
        - containerPort: 9081
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: ms-participantes-config
              key: APP_NAME
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: ms-participantes-config
              key: SERVER_PORT
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: ms-participantes-config
              key: DB_URL
        - name: DB_DRIVER
          valueFrom:
            configMapKeyRef:
              name: ms-participantes-config
              key: DB_DRIVER
        - name: JPA_DDL_AUTO
          valueFrom:
            configMapKeyRef:
              name: ms-participantes-config
              key: JPA_DDL_AUTO
        - name: JPA_SHOW_SQL
          valueFrom:
            configMapKeyRef:
              name: ms-participantes-config
              key: JPA_SHOW_SQL
        - name: HIBERNATE_DIALECT
          valueFrom:
            configMapKeyRef:
              name: ms-participantes-config
              key: HIBERNATE_DIALECT
        - name: EVENTOS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ms-participantes-config
              key: EVENTOS_SERVICE_URL