ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER dkeventos IDENTIFIED BY pwdeventos;
GRANT CONNECT, RESOURCE TO dkeventos;
ALTER USER dkeventos QUOTA UNLIMITED ON users;

-- Cambiar al esquema del usuario recién creado
ALTER SESSION SET CURRENT_SCHEMA = DKEVENTOS;

-- Crear la tabla en el esquema DKEVENTOS
CREATE TABLE EVENTO (
    CODIGO_EVENTO VARCHAR(20) PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    DESCRIPCION VARCHAR(255),
    FECHA_HORA TIMESTAMP NOT NULL,
    UBICACION VARCHAR(255) NOT NULL,
    CAPACIDAD_MAXIMA INT NOT NULL
);

-- Datos iniciales
INSERT INTO EVENTO (CODIGO_EVENTO, NOMBRE, DESCRIPCION, FECHA_HORA, UBICACION, CAPACIDAD_MAXIMA)
VALUES ('EVT202505141', 'Conferencia Tech', 'Evento tecnológico', TO_TIMESTAMP('2025-06-20 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Lima', 100);

COMMIT;
